Improve how we handle our binaries
* All binaries are now self-documenting!
  * All binaries have a '--help' function
  * The contents of the '--help' function are now automatically
    reflected in the README
* Added bats testing framework for binaries.

Signed-off-by: Tom Duffield <tom@chef.io>

diff --git a/bin/citadel b/bin/citadel
--- a/bin/citadel
+++ b/bin/citadel
@@ -16,37 +16,57 @@
 # limitations under the License.
 #
 
+export CITADEL_PROFILE="${CITADEL_PROFILE:-$AWS_PROFILE}"
+export CITADEL_BUCKET="${CITADEL_BUCKET:-${AWS_PROFILE}-citadel}"
+
+function enforce_requirements() {
+  # Make sure the AWS CLI is installed
+  which aws &>/dev/null
+  if [[ $? -ne 0 ]]; then
+    echo "${0##*/}: Unable to find 'aws' executable."
+    echo "Make sure you have the aws cli installed. Try 'install-tool aws'."
+    exit 2
+  fi
+
+  # Make sure the necessary profile is configured
+  aws-configure is-configured $CITADEL_PROFILE &>/dev/null
+  if [[ $? -ne 0 ]]; then
+    echo "${0##*/}: The '$CITADEL_PROFILE' aws profile is not configured."
+    echo "Make sure you have '$CITADEL_PROFILE' configured. Try 'aws-configure $CITADEL_PROFILE'"
+    exit 2
+  fi
+}
+
 function usage() {
   cat /dev/stdin <<DOC
 Usage: ${0##*/} FILE
 
 A Bash utility that prints the contents of the given FILE from the CITADEL_BUCKET in S3 to STDOUT.
 
+Requires that you have an AWS profile configured. To configure an AWS profile, you can use 'aws-configure [PROFILE]'.
+
 ENVIRONMENT VARIABLES:
-    CITADEL_BUCKET      The name of the S3 bucket where citadel files are kept. (default: chef-cd-citadel)
-    CITADEL_PROFILE     The name of the AWS CLI profile with access to citadel. (default: chef-cd)
+    CITADEL_BUCKET        The name of the S3 bucket where citadel files are kept. (default: \$AWS_PROFILE-citadel)
+    CITADEL_PROFILE       The name of the AWS CLI profile with access to citadel. (default: \$AWS_PROFILE)
 DOC
 }
 
-function enforce_requirements() {
-  # Make sure the AWS CLI is installed
-  which aws >/dev/null &2>1
-  if [[ $? -ne 0 ]]; then
-    echo "${0##*/}: Unable to find 'aws' executable."
-    echo "Make sure you have the aws cli installed. Try 'install-tool aws'."
-    exit 2
-  fi
+function get_file() {
+  enforce_requirements
+
+  file="$1"
+  aws s3 cp --profile $CITADEL_PROFILE s3://$CITADEL_BUCKET/$file -
 }
 
 case "$1" in
-  "-h"|"--help"|"")
+  "-h"|"--help")
     usage
     ;;
+  "")
+    usage
+    exit 1
+    ;;
   *)
-    profile="${CITADEL_PROFILE:-chef-cd}"
-    bucket="${CITADEL_BUCKET:-chef-cd-citadel}"
-    file="$1"
-
-    aws s3 cp --profile $profile s3://$bucket/$file -
+    get_file $1
     ;;
 esac
