Tons of updates to bring ci-studio-common back the darkness
* Add 'did-modify' CLI utility - This utility detects if files have been modified via git
* Update tests to use bats-mock
* Add dedicated binary for configuring github account
* Deprecated the hab-studio binary now that we have proper secrets in hab
* Remove support for handling AWS_PROFILE natively. It breaks aws-cli.
* Move to Buildkite and fix hab-origin issues
* Move to use the buildkite/plugin-tester image to bats testing
* Fix issue where we were failing to install the origin key correctly

Signed-off-by: Tom Duffield <tom@chef.io>

diff --git a/bin/studio-common b/bin/studio-common
--- a/bin/studio-common
+++ b/bin/studio-common
@@ -17,66 +17,67 @@
 # limitations under the License.
 #
 
+set -eou pipefail
+
 # Error out if someone tries to execute this script, rather than sourcing it.
-if [[ "$BASH_SOURCE" == "$0" ]];
-then
-  cat /dev/stdin <<'DOC'
+if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
+  cat <<'DOC'
 ERROR: studio-common is designed to be sourced, not executed. Please source this file as exemplified below:
 
   source "$(hab pkg path chef/ci-studio-common)/bin/studio-common"
 
 DOC
   exit 1
-fi;
+fi
 
 # This value is automatically updated by Expeditor to reflect .hab-version
-export SUPPORTED_HAB_VERSION="0.54.0";
+export SUPPORTED_HAB_VERSION="0.54.0"
 
 # Ensure that the installed version of the hab toolchain is >= to the required version.
 #
 # Given the rapid development and release cadence of Habitat, we want to ensure that
 # developers are using a version of Habitat is is well tested against both this library
 # and the supporting automation (i.e. Expeditor builds).
-required_version="$SUPPORTED_HAB_VERSION";
-installed_version=$(hab -V | awk '{print $NF}' | cut -f1 -d/);
+required_version="$SUPPORTED_HAB_VERSION"
+installed_version=$(hab -V | awk '{print $NF}' | cut -f1 -d/)
 
-MAJOR=$(echo "$installed_version"  | cut -f1 -d.);
-MINOR=$(echo "$installed_version"  | cut -f2 -d.);
-PATCH=$(echo "$installed_version"  | cut -f3 -d.);
-R_MAJOR=$(echo "$required_version" | cut -f1 -d.);
-R_MINOR=$(echo "$required_version" | cut -f2 -d.);
-R_PATCH=$(echo "$required_version" | cut -f3 -d.);
+MAJOR=$(echo "$installed_version"  | cut -f1 -d.)
+MINOR=$(echo "$installed_version"  | cut -f2 -d.)
+PATCH=$(echo "$installed_version"  | cut -f3 -d.)
+R_MAJOR=$(echo "$required_version" | cut -f1 -d.)
+R_MINOR=$(echo "$required_version" | cut -f2 -d.)
+R_PATCH=$(echo "$required_version" | cut -f3 -d.)
 
-need_upgrade=false;
-is_newer=false;
+need_upgrade=false
+is_newer=false
 
-[[ $PATCH -lt $R_PATCH ]] && need_upgrade=true;
-[[ $PATCH -gt $R_PATCH ]] && is_newer=true;
+[[ $PATCH -lt $R_PATCH ]] && need_upgrade=true
+[[ $PATCH -gt $R_PATCH ]] && is_newer=true
 
 if [[ $MINOR -ne $R_MINOR ]]; then
-  [[ $MINOR -lt $R_MINOR ]] && need_upgrade=true || need_upgrade=false;
-  [[ $MINOR -gt $R_MINOR ]] && is_newer=true || is_newer=false;
-fi;
+  [[ $MINOR -lt $R_MINOR ]] && need_upgrade=true || need_upgrade=false
+  [[ $MINOR -gt $R_MINOR ]] && is_newer=true || is_newer=false
+fi
 if [[ $MAJOR -ne $R_MAJOR ]]; then
-  [[ $MAJOR -lt $R_MAJOR ]] && need_upgrade=true || need_upgrade=false;
-  [[ $MAJOR -gt $R_MAJOR ]] && is_newer=true || is_newer=false;
-fi;
+  [[ $MAJOR -lt $R_MAJOR ]] && need_upgrade=true || need_upgrade=false
+  [[ $MAJOR -gt $R_MAJOR ]] && is_newer=true || is_newer=false
+fi
 
 if $need_upgrade; then
-  echo "ERROR: Habitat needs to be upgraded to version '$SUPPORTED_HAB_VERSION'";
-  echo "       Run:";
-  echo "       => hab studio rm";
-  echo "       to remove the studio, and then";
-  echo "       => curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash -s -- -v $SUPPORTED_HAB_VERSION";
+  echo "ERROR: Habitat needs to be upgraded to version '$SUPPORTED_HAB_VERSION'"
+  echo "       Run:"
+  echo "       => hab studio rm"
+  echo "       to remove the studio, and then"
+  echo "       => curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash -s -- -v $SUPPORTED_HAB_VERSION"
   exit 1
 fi;
 
 if $is_newer; then
-  echo "WARNING: Version '$installed_version' of Habitat has not been fully tested for compatibility with ci-studio-common.";
-  echo "         Please consider exiting the studio, running:";
-  echo "         => hab studio rm";
-  echo "         to remove the studio, and then";
-  echo "         => curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash -s -- -v $SUPPORTED_HAB_VERSION";
+  echo "WARNING: Version '$installed_version' of Habitat has not been fully tested for compatibility with ci-studio-common."
+  echo "         Please consider exiting the studio, running:"
+  echo "         => hab studio rm"
+  echo "         to remove the studio, and then"
+  echo "         => curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash -s -- -v $SUPPORTED_HAB_VERSION"
 fi;
 
 # Assuming we have the correct version of Habitat installed, we can proceed.
@@ -87,8 +88,7 @@ export PLAN_CONTEXT="${PLAN_CONTEXT:-/src/habitat}"
 [[ -f /src/habitat/default.toml ]] && export TOML_FILE=/src/habitat/default.toml
 
 # The folder where all the documentation is stored
-[[ ! -d /tmp/docs ]] && mkdir /tmp/docs
-[[ ! -d /tmp/aliases ]] && mkdir /tmp/aliases
+mkdir -p /tmp/docs /tmp/aliases
 
 # This is a helper function that allows use to document functions inline with the
 # code, but also make that documentation available to end user in the studio.
@@ -101,7 +101,7 @@ function document() {
   name="$1"
   content=$(cat /dev/stdin)
 
-  [ -z "$CI" ] && echo -e "$content" > "/tmp/docs/${name}"
+  [[ -z "${CI:-}" ]] && echo -e "$content" > "/tmp/docs/${name}"
 }
 
 # This is a helper function that allows you to quickly and easily add an alias for
@@ -112,7 +112,7 @@ function add_alias() {
   a="$2"
 
   eval "alias $a=$fun"
-  [ -z "$CI" ] && echo -e "$a" > "/tmp/aliases/$fun"
+  [[ -z "${CI:-}" ]] && echo -e "$a" > "/tmp/aliases/$fun"
 }
 
 # This function allows the user to learn more about the studio.
@@ -120,46 +120,44 @@ function add_alias() {
 #   1. Passing no argument will print out a list of all documented functions
 #   2. Passing the name of a function will print out that functions documentation
 function describe() {
-  if [ -z "$CI" ]
-  then
-    echo ""
+  if [[ -z "${CI:-}" ]]; then
+    echo
     if [[ -z "$1" ]]; then
       echo "The following functions are available for your use in this studio:"
-      echo ""
+      echo
       for file in /tmp/docs/*
       do
         fun="$(basename "$file")"
-        printf "  $fun"
-        [[ -f "/tmp/aliases/$fun" ]] && printf " [alias: $(cat /tmp/aliases/$fun)]"
-        printf "\n"
+        echo -n "  $fun"
+        [[ -f "/tmp/aliases/$fun" ]] && printf " [alias: %s]" "$(cat /tmp/aliases/"$fun")"
+        echo
         echo "  $(head -n 1 "$file")"
       done
       if [[ -d "/tmp/aliases" ]]; then
-        echo ""
+        echo
         echo "ALIASES:"
         for a in /tmp/aliases/*
         do
-          printf "  %-6s Alias for: %s \n" "$(cat $a)" "$(basename "$a")"
+          printf "  %-6s Alias for: %s \\n" "$(cat "$a")" "$(basename "$a")"
         done
       fi
-      echo ""
+      echo
       echo "To learn more about a particular function, run 'describe <function>'."
     else
       cat "/tmp/docs/$1"
     fi
-    echo ""
+    echo
   fi
 }
 
 # This function allows the user to print a nice "welcome" or "getting started"
 # message when a new user enters the studio.
 function getting_started() {
-  [ -z "$CI" ] && cat /dev/stdin
+  [[ -z "${CI:-}" ]] && cat /dev/stdin
 }
 
 # Source the .secrets file (if it exists)
-if [ -f /src/.secrets ]
-then
+if [[ -f /src/.secrets ]]; then
   source /src/.secrets
 fi
 
@@ -167,7 +165,7 @@ source_msg="Helpers from ci-studio-common"
 
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 dot_studio_dir="$script_dir/../dot-studio"
-if ! [ -d "$dot_studio_dir" ]; then
+if ! [[ -d "$dot_studio_dir" ]]; then
   echo "ERROR: Expected dot-studio directory at $(realpath "$dot_studio_dir")"
   exit 1
 fi
@@ -179,8 +177,7 @@ done
 
 # Source all the files available in the .studio directory of the /src directory
 # Only if the '.studio/' directory exists and it is not empty
-if [ "$(ls -A /src/.studio 2>/dev/null)" ]
-then
+if ls -A /src/.studio &>/dev/null; then
   for file in /src/.studio/*
   do
     source "$file"
diff --git a/dot-studio/hab_toolchain b/dot-studio/hab_toolchain
--- a/dot-studio/hab_toolchain
+++ b/dot-studio/hab_toolchain
@@ -74,12 +74,12 @@ function install() {
 
   if [[ "x$1" == "x" ]]; then
     # Trying to use the last package built
-    pushd /src >/dev/null
-      # If there are no packages available, build one for me
-      [[ ! -f results/last_build.env ]] && build .;
-      source results/last_build.env;
-      eval "hab pkg $install_cmd results/${pkg_artifact} >/dev/null";
-    popd >/dev/null;
+    cd /src || return
+    # If there are no packages available, build one for me
+    [[ ! -f results/last_build.env ]] && build .
+    source results/last_build.env
+    eval "hab pkg $install_cmd results/$pkg_artifact >/dev/null"
+    cd ../ || return
   else
     for pkg in "$@"
     do
@@ -96,29 +96,27 @@ document "export_docker_image" <<DOC
   If no last_build.env file is present, it will perform a build automatically.
 DOC
 function export_docker_image() {
-  pushd /src >/dev/null;
-    if [[ ! -f results/last_build.env ]]; then
-        echo "=> No Habitat build found - building now. [please wait]";
-        build >/dev/null;
-        [[ $? -ne 0 ]] && return 1;
-    fi;
-    source results/last_build.env;
-    echo "=> Latest build: $pkg_artifact";
-    echo "=> Exporting Habitat package into a Docker image. [please wait]";
-    hab pkg export docker "results/${pkg_artifact}" >/dev/null
-    if [[ $? -ne 0 ]]; then
-        # If something went wrong here is because the pkg export cmd failed
-        echo "Unable to export package as a Docker Image.";
-        echo "Run 'hab pkg export docker \"$pkg_artifact\"' and diagnose.";
-        popd > /dev/null;
-        return 1;
-    fi;
-    export DOCKER_TAG="${pkg_version}-${pkg_release}";
-    export DOCKER_REPO="${pkg_origin}/${pkg_name}";
-    export DOCKER_IMAGE="${DOCKER_REPO}:${DOCKER_TAG}";
-    echo "=> Docker image successfully built: $DOCKER_IMAGE";
-    echo "=> Now you can use the image '$DOCKER_REPO' on any 'docker-compose.yml'";
-  popd >/dev/null
+  cd /src || return
+  if [[ ! -f results/last_build.env ]]; then
+    echo "=> No Habitat build found - building now. [please wait]"
+    build >/dev/null && return 1
+  fi
+  source results/last_build.env
+  echo "=> Latest build: $pkg_artifact"
+  echo "=> Exporting Habitat package into a Docker image. [please wait]"
+  if ! hab pkg export docker "results/${pkg_artifact}" >/dev/null; then
+    # If something went wrong here is because the pkg export cmd failed
+    echo "Unable to export package as a Docker Image."
+    echo "Run 'hab pkg export docker \"$pkg_artifact\"' and diagnose."
+    cd ../ || return
+    return 1
+  fi
+  export DOCKER_TAG="${pkg_version}-${pkg_release}"
+  export DOCKER_REPO="${pkg_origin}/${pkg_name}"
+  export DOCKER_IMAGE="${DOCKER_REPO}:${DOCKER_TAG}"
+  echo "=> Docker image successfully built: $DOCKER_IMAGE"
+  echo "=> Now you can use the image '$DOCKER_REPO' on any 'docker-compose.yml'"
+  cd ../ || return
 }
 
 document "install_if_missing" <<DOC
@@ -136,8 +134,7 @@ function install_if_missing() {
   fi
 
   # Install the package if it is not installed
-  if [[ ! -d "/hab/pkgs/$1" ]];
-  then
+  if [[ ! -d "/hab/pkgs/$1" ]]; then
     install "$1"
   else
     echo "$(hab pkg path "$1") is already installed"
diff --git a/dot-studio/studio_setup b/dot-studio/studio_setup
--- a/dot-studio/studio_setup
+++ b/dot-studio/studio_setup
@@ -29,13 +29,13 @@ document "generate_netrc_config" <<DOC
 DOC
 function generate_netrc_config() {
   if [[ -z "$GITHUB_TOKEN" ]]; then
-    echo -e "\nError: Unable to configure ~/.netrc in the studio."
+    echo -e "\\nError: Unable to configure ~/.netrc in the studio."
     echo "Missing the environment variable: GITHUB_TOKEN"
-    echo -e "\nVerify that you have a file called '.secrets' with the following export:"
+    echo -e "\\nVerify that you have a file called '.secrets' with the following export:"
     echo "export GITHUB_TOKEN=[your-secret-token]"
     exit 1
   else
-    echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
+    echo -e "machine github.com\\n  login $GITHUB_TOKEN" >> ~/.netrc
   fi
 }
 
@@ -61,8 +61,7 @@ function clone_function() {
   local function="$1"
 
   # Return an error if that is not a defined function
-  if [[ ! -f /tmp/docs/$function ]]
-  then
+  if [[ ! -f /tmp/docs/$function ]]; then
     echo "ERROR: ci-studio-common does not provide a '$function' function."
     return
   fi
@@ -71,8 +70,7 @@ function clone_function() {
   mkdir -p /src/.studio > /dev/null
 
   # Create the override-common file if it's Missing
-  if [[ ! -f /src/.studio/override-common ]]
-  then
+  if [[ ! -f /src/.studio/override-common ]]; then
     cat << EOF > /src/.studio/override-common
 #!/bin/bash
 # In this file, you can override functions included with ci-studio-common to meet your needs.
@@ -82,14 +80,13 @@ EOF
 
   # Add the contents of the function to the override file unless it has already
   # been overridden.
-  if ! grep -w "$function\(\)" /src/.studio/override-common > /dev/null
-  then
+  if ! grep -w "$function\\(\\)" /src/.studio/override-common > /dev/null; then
     cat << EOF >> /src/.studio/override-common
 
 document "$function" <<DOC
-$(cat /tmp/docs/$function)
+$(cat /tmp/docs/"$function")
 DOC
-function `declare -f $function`
+function $(declare -f "$function")
 EOF
     echo "A copy of the '$function' function has been added to /src/.studio/override-common."
   else
