Enforce specific version of Habitat
Ensure that the installed version of the hab toolchain is >= to the
required version.

Given the rapid development and release cadence of Habitat, we want to
ensure that developers are using a version of Habitat is is well tested
against both this library and the supporting automation (i.e. Expeditor)

Signed-off-by: Tom Duffield <tom@chef.io>

diff --git a/bin/studio-common b/bin/studio-common
--- a/bin/studio-common
+++ b/bin/studio-common
@@ -17,6 +17,52 @@
 # limitations under the License.
 #
 
+# This value is automatically updated by Expeditor to reflect .hab-version
+export SUPPORTED_HAB_VERSION="0.34.1"
+
+# Ensure that the installed version of the hab toolchain is >= to the required version.
+#
+# Given the rapid development and release cadence of Habitat, we want to ensure that
+# developers are using a version of Habitat is is well tested against both this library
+# and the supporting automation (i.e. Expeditor builds).
+required_version="$SUPPORTED_HAB_VERSION"
+installed_version=$(hab -V | awk '{print $NF}' | cut -f1 -d/);
+
+MAJOR=$(echo "$installed_version"  | cut -f1 -d.);
+MINOR=$(echo "$installed_version"  | cut -f2 -d.);
+PATCH=$(echo "$installed_version"  | cut -f3 -d.);
+R_MAJOR=$(echo "$required_version" | cut -f1 -d.);
+R_MINOR=$(echo "$required_version" | cut -f2 -d.);
+R_PATCH=$(echo "$required_version" | cut -f3 -d.);
+
+need_upgrade=false;
+is_newer=false;
+
+[[ $PATCH -lt $R_PATCH ]] && need_upgrade=true;
+if [[ $MINOR -ne $R_MINOR ]]; then
+  [[ $MINOR -lt $R_MINOR ]] && need_upgrade=true || need_upgrade=false;
+  [[ $MINOR -gt $R_MINOR ]] && is_newer=true || is_newer=false;
+fi;
+if [[ $MAJOR -ne $R_MAJOR ]]; then
+  [[ $MAJOR -lt $R_MAJOR ]] && need_upgrade=true || need_upgrade=false;
+  [[ $MAJOR -gt $R_MAJOR ]] && is_newer=true || is_newer=false;
+fi;
+
+if $need_upgrade; then
+  echo "ERROR: Habitat needs to be upgraded to version '$SUPPORTED_HAB_VERSION'"
+  echo "       Exit the studio and run the command:"
+  echo "       => curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash -s -- -v $SUPPORTED_HAB_VERSION"
+  exit 1
+fi;
+
+if $is_newer; then
+  echo "WARNING: Version '$1' of Habitat has not been fully tested for compatibility with ci-studio-common."
+  echo "         Please consider exiting the studio and running the following command to install the recommended version:"
+  echo "         => curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash -s -- -v $SUPPORTED_HAB_VERSION"
+fi;
+
+# Assuming we have the correct version of Habitat installed, we can proceed.
+
 # Source the plan.sh and default.toml files (if they exist)
 [[ -f /src/habitat/plan.sh ]] && source /src/habitat/plan.sh
 [[ -f /src/habitat/default.toml ]] && export TOML_FILE=/src/habitat/default.toml
